services:
  trafficserver:
    image: cfdh.zjusct.io/trafficserver/trafficserver
    container_name: trafficserver
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - ./config:/opt/etc/trafficserver
      - ./cert:/ca
      - ./var:/opt/var/
      
